### ISSUE TITLE
TypeError: Atrium is not a constructor

### ISSUE THREAD

**Issue by Divyasam** [mxenabled/mx-atrium-node#25]
const atriumApi = new Atrium(apiKey, clientId, url);
Getting error while using the above command.
Also, what has to be specified in the url?

**Comment by minond** [comment]
Can you include more information? The full error output as well as all how you executed your code?

**Comment by Divyasam** [comment]
const Atrium = require('mx-atrium');
const atriumApi = new Atrium(api_key, client_id);
This is the code that i tried to  use. I used the api key and client id provided by mx while creating a developer account. 
Error:
[0] TypeError: Atrium is not a constructor
[0]     at Object.<anonymous> (C:\Users\optellent\Desktop\charter\charter\server\server.js:10:19)
[0]     at Module._compile (internal/modules/cjs/loader.js:688:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
[0]     at Module.load (internal/modules/cjs/loader.js:598:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
[0]     at startup (internal/bootstrap/node.js:285:19)
[0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by minond** [comment]
The correct usage is like this:

```
const atrium = require("mx-atrium")

const client = new atrium.AtriumClient("YOUR_REAL_API_KEY_GOES_HERE", "YOUR_REAL_CLIENT_ID_GOES_HERE");
```

**Comment by Divyasam** [comment]
Can you please update the same under Wiki tab. There its been mentioned as
new Atrium()

**Comment by minond** [comment]
Done. Thanks for the heads up.
